version: "3"
services:
  invoice_ocr:
    build: ./invoice_ocr_service
    ports:
      - "8000:8000"

  resume_parser:
    build: ./resume_parser_service
    ports:
      - "8001:8001"

  email_summarizer:
    build: ./email_summarizer_service
    ports:
      - "8002:8002"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./monitor/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - resume_parser
      - invoice_ocr
      - email_summarizer
      - api_gateway

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  grafana-data:
